apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: amadop
  labels:
    app: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: ClusterIP
