apiVersion: v1
kind: ConfigMap
metadata:
  name: amadop-config
  namespace: amadop
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/amadop_db"
  AUTH_SERVICE_URL: "http://auth-service:8001"
  POST_SERVICE_URL: "http://post-service:8002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8004"
  CORS_ORIGINS: '["http://localhost:5173","http://localhost:30573"]'
  AI_SERVICE_URL: "http://ai-service:8005"
  PROMETHEUS_URL: "http://prometheus-server.amadop.svc.cluster.local"
  SCAN_INTERVAL_SECONDS: "30"
  ALERT_COOLDOWN_SECONDS: "300"
  ADMIN_USER_IDS: "[1]"
